package com.cooksys.hibernate;

// Generated May 11, 2015 3:02:23 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tweets generated by hbm2java
 */
@Entity
@Table(name = "tweets", catalog = "twitterbaby")
public class Tweets implements java.io.Serializable {

	private Integer tweetid;
	private String username;
	private String message;

	public Tweets() {
	}

	public Tweets(String username, String message) {
		this.username = username;
		this.message = message;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "tweetid", unique = true, nullable = false)
	public Integer getTweetid() {
		return this.tweetid;
	}

	public void setTweetid(Integer tweetid) {
		this.tweetid = tweetid;
	}

	@Column(name = "username", nullable = false, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "message", nullable = false, length = 45)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

}
